# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fcbeabf736ffa56fa38ebe1eb2b8dd9f0b1859588ae70cd6bb18bcd7513bd79c6aa2e7be011d33f1b9d7b5744b913e427ec145fb61a7f462f595cf6efb9f601

test:
  secret_key_base: 41e60e430c14c406da29c66a7f4cb86d12610da05fb79f09b6f38a30914918cdd78a301b76a65d785678268170cbc2c6280a3f5ea9a41301bf2d4f78ccda9aeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
